"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](bg:lavender)$os$username\
[](bg:sky fg:lavender)$directory\
[](fg:sky bg:teal)$git_branch$git_status\
[](fg:teal bg:green)$c$rust$golang$nodejs$php$java$kotlin$haskell$python\
[](fg:green bg:yellow)$docker_context$conda\
[](fg:yellow bg:peach)$time\
[](fg:peach bg:maroon)$cmd_duration\
[](fg:maroon)\
$line_break$character
"""

palette = 'catppuccin_frappe'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text_color = "#303446"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"


[os]
disabled = false
style = "bg:lavender fg:text_color"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[username]
show_always = true
style_user = "bg:lavender fg:text_color"
style_root = "bg:lavender fg:text_color"
format = '[ $user ]($style)'

[directory]
style = "fg:text_color bg:sky"
format = "[ $path ]($style)"
truncation_length = 7
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Projects" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:text_color bg:teal)]($style)'

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:text_color bg:teal)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:text_color bg:green)]($style)'

[elixir]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:text_color bg:green)]($style)'

[elm]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:text_color bg:green)]($style)'

[nim]
symbol = "󰆥 "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:text_color bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:text_color bg:green)]($style)'

[julia]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:text_color bg:green)]($style)'

[scala]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:text_color bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol ( $toolchain) ($version) ](fg:text_color bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:text_color bg:green)]($style)'

[php]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:text_color bg:green)]($style)'

[java]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:text_color bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:text_color bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:text_color bg:green)]($style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol ( $pyenv_prefix) ($virtualenv) ($version) ](fg:text_color bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol( $context) ](fg:#83a598 bg:yellow)]($style)'

[conda]
style = "bg:yellow"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:yellow)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:peach"
format = '[[  $time ](fg:text_color bg:peach)]($style)'

[cmd_duration]
format = "[ 󱎫 $duration](fg:text_color bg:maroon)"
min_time = 500

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:maroon)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:sky)'
